version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://finsight:password@postgres:5432/finsight
      - JWT_SECRET=dev-secret-key-change-in-production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - finsight-network

  frontend-build:
    build: ./frontend
    volumes:
      - ./frontend/build:/app/build
    command: echo "Frontend built for Firebase hosting"
    networks:
      - finsight-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=finsight
      - POSTGRES_USER=finsight
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finsight-network

volumes:
  postgres_data:

networks:
  finsight-network:
    driver: bridge 